.TH DTAR 1 "DTar Manual"
.SH NAME
dtar \- housekeeping and meta-commands for the DTar suite
.SH SYNOPSIS
.B dtar
[\-help] [\-version]
.SH DESCRIPTION
The dtar utility provides housekeeping commands for the DTar suite, such as displaying help and version information.
.SH OPTIONS
.TP
.B \-help
Show help message.
.TP
.B \-version
Show version information.